--- # ANSIBLE PLAYBOOK TO CONFIGURE STATIC WEB SERVER AND USE IT TO CREATE NEW TEMPLATE
- hosts: AWS
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  tasks: 
  - name: Install all the items
    yum: name={{ item }} state=latest
    with_items:
     - httpd
     - wget
    notify: 
     - CopySiteFiles
     - RestartHTTPD
     - WaitForSite
     - TestSite
     - DisplayResult 
  handlers: 
  - name: CopySiteFiles
    copy: 
     src: ../files/index.html 
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0655
     backup: yes
  - name: RestartHTTPD
    service: 
     name: httpd
     state: restarted
  - name: WaitForSite
    wait_for: 
     host: 52.66.123.53
     port: 80
     delay: 5
  - name: TestSite
    shell: /usr/bin/wget http://localhost
    register: site_result
  - name:  DisplayResult
    debug: var=site_result

- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - ../files/awscreds.yml
  tasks:
  - name: Take a snapshot backup of website directory
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-02bacc65cd038e12c
      device_name: /dev/sdg
      description: Initial playbook static site deployment backup
      wait: no
    register: snapshot_result
    notify: 
    - DisplaySnapshotResults
    - CreateNewAMITemplate
    - DisplayAMICreationResults
  handlers:
  - name: DisplaySnapshotResults
    debug: var=snapshot_result
  - name: CreateNewAMITemplate
    ec2_ami:
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     instance_id: i-02bacc65cd038e12c
     wait: no
     name: MyAnsibleAMITemplate
     tags:
      Name: MyNewAnsibleAMITemplate
      Service: TestAMITemplatePlaybook
    register: ami_result
  - name: DisplayAMICreationResults
    debug: var=ami_result
