--- # ANSIBLE PLAYBOOK TO CONFIGURE STATIC WEB SERVER AND USE IT TO CREATE NEW TEMPLATE
- hosts: AWS
  connection: ssh
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  tasks: 
  - name: Connect to remote host and execute yum update
    yum: name=* state=latest
  - name: Install the HTTPD Server
    yum:
      name: httpd
      state: latest
  - name: Deploy Static Website
    copy: 
     src: ../files/index.html 
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0655
     backup: yes
  - name: Restart HTTPD Service
    service: 
     name: httpd
     state: restarted
  - name: Wait for the HTTPD port 8- to listen
    wait_for: 
     host: 52.66.123.53
     port: 80
     delay: 5
  - name: Install WGET to test the site
    yum:
     name: wget
     state: latest
  - name: Test the Site
    shell: /usr/bin/wget http://localhost
    register: site_result
  - name:  Displaye Site Output Result
    debug: var=site_result

- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - ../files/awscreds.yml
  tasks:
  - name: Take a snapshot backup of website directory
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-02bacc65cd038e12c
      device_name: /dev/sdg
      description: Initial playbook static site deployment backup
      wait: no
    register: snapshot_result
  - name: debug output
    debug: var=snapshot_result
  - name: Create a New Template AMI from our Instance
    ec2_ami:
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     instance_id: i-02bacc65cd038e12c
     wait: no
     name: MyAnsibleAMITemplate
     tags:
      Name: MyNewAnsibleAMITemplate
      Service: TestAMITemplatePlaybook
    register: ami_result
  - name: Display the AMI Creation Results
    debug: var=ami_result
