--- # EC2 AMI EXAMPLE FOR CREATING AMI TEMPLATE FROM EXISTING RUNNING INSTANCE
- hosts: localhost
  remote_user: ansible
  connection: local
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: CREATE AMI TEMPLATE FROM EXISTING RUNNING INSTANCE
    ec2_ami:
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       instance_id: i-0098e6ba5dbdee06f
       wait: no
       name: mynewami2
       tags: 
         Name: MyNewAMI2
         Service: MyNewAMIService2
       device_mapping: 
         - device_name: /dev/sdb1
           size: 100
           delete_on_termination: true
           volume_type: gp2
    register: instance
