--- # PROVISION EC2 INSTANCE
- hosts: localhost
  remote_user: local
  connection: local
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks:
  - name: add ec2 instance
    ec2: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: ami-d783a9b8
      count: 2
      vpc_subnet_id: subnet-3570005d
      instance_type: t2.micro
      assign_public_ip: yes
      
