--- # AWS EC2 ALARM METRICS
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks: 
  - name: AWS EC2 ALARM METRICS
    ec2_metric_alarm:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      state: present
      name: firstAlarmTest
      metric: "CPUUTILIZATION"
      namespace: "AWS/EC2"
      statistic: Average
      comparison: ">="
      threshold: 25.0
      unit: "Percent"
      period: 300
      evaluation_periods: 6
      description: "This alarm fires when CPU is greater than 25% for 30 minutes"
      dimensions: {'InstanceID':'i-09c072db576da8f44'}
