--- # SEARCH VOLUME AND TAG IT
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks:
  - name: Search Volume and tag it
    ec2_tag:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      resource: vol-0e1b402a5878fc7cb
      state: present
      tags:
        Name: data_volume
    register: voltag
