--- # CREATE SNAPSHOT
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create SNAPSHOT
    ec2_snapshot: 
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       instance_id: i-09c072db576da8f44
       device_name: /dev/xvda
       description: "Root Volume Snapshot"
       wait: no
    register: snapshot
  - debug: msg={{ snapshot }}
