--- # Create VPC
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks: 
  - name: Create VPC
    ec2_vpc:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"    
      state: present
      cidr_block: 192.2.1.0/16
    register: vpc
