--- # EC2 VPC FACTS
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  -  files/awscreds.yml
  tasks:
  - name: EC2 VPC FACTS
    ec2_vpc_net_facts: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      filters:
        vpc-id: vpc-00743c68
    register: vpcnetfacts
  - name: Get the registered out-put
    debug: msg={{ vpcnetfacts.vpcs[0].id }}
