--- #EC2 STATE MANAGEMENT
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks: 
  - name: change the state of aws ec2 instance
    ec2: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_ids: "{{ item }}"
      state: absent
    with_items: 
        - i-04a8cab25835479bc
        - i-04afe7883ba870ea7
        - i-09dd9b1abf0443492
        - i-0a9886e6b1aab870f
