--- # CREATE SNAPSHOT
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create SNAPSHOT
    ec2_snapshot: 
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       snapshot_id: snap-031219155edbe22a2
       state: absent
       wait: no
    register: snapshot
  - debug: msg={{ snapshot }}
