--- # Create IAM Users
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create IAM Users (Anisble)
    iam: 
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     iam_type: user
     name: "{{ item }}"
     state: present
     password: "password"
     access_key_state: create
    with_items:
     - temp1
     - temp2
    register: output
  - name: Print Output on Linux Command Prompt
    debug: msg={{ output }} 
