--- # AWS S3 BUCKET CREATION
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: yes
  vars_files: 
  - files/awscreds.yml
  tasks:
  - name: AWS S3 BUCKET CREATION
    s3:
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     bucket: ansibleplay
     mode: delete
     permission: public-read-write
    register: Create_Bucket
